import { selectRenderedText } from './preview.js'

export async function runPerformanceSuite({ client, assert, pause, until, sync, same, log }) {
  const source = Array.from({ length: 250 }, (_, n) => `## 第 ${n + 1} 节\n这是 **协作编辑** 的千行性能测试，包含 [链接](#/r/example) 和中文 emoji 😀。\n更多普通内容与行内代码 \`const value = ${n}\`。\n`).join('\n')
  const percentile = (values, q) => [...values].sort((a, b) => a - b)[Math.min(values.length - 1, Math.floor(values.length * q))].toFixed(1)
  for (const mode of ['edit', 'split']) {
    const a = await client(mode), b = await client(mode)
    await a.api.bootstrap(source); await b.api.load(a.api.checkpoint())
    await until(() => a.api.view() && b.api.view(), 'large editors not ready')
    await pause(1500)
    a.api.remember(); b.api.remember(); a.api.takeUpdates(); b.api.takeUpdates()
    let paints = 0
    const article = a.dom.querySelector('.markdown-body')
    const observer = new a.dom.defaultView.MutationObserver(() => paints++)
    if (article) observer.observe(article, { subtree: true, childList: true, characterData: true })
    const dispatch = [], cadence = []
    const start = performance.now()
    a.api.select(10)
    for (let n = 0; n < 30; n++) {
      const tick = performance.now()
      a.api.insert('x'); sync(a, b)
      dispatch.push(performance.now() - tick)
      await pause(25)
      cadence.push(performance.now() - tick)
    }
    const elapsed = performance.now() - start
    await pause(1000)
    same(a, b)
    assert(a.api.stable() && b.api.stable(), 'typing rebuilt editor')
    assert(b.api.count().pending === 0, 'remote update echoed')
    if (article) assert(article.textContent.includes('xxx'), 'preview did not catch up')
    log(`${mode}: 1000 lines / ${source.length} UTF-16 chars / 30 updates; dispatch p50=${percentile(dispatch,.5)}ms p95=${percentile(dispatch,.95)}ms; input cadence p50=${percentile(cadence,.5)}ms p95=${percentile(cadence,.95)}ms (25ms target); elapsed=${elapsed.toFixed(1)}ms; preview commits=${paints}`)
    observer.disconnect()
    a.api.dispose(); b.api.dispose()
    a.dom.defaultView.frameElement.remove(); b.dom.defaultView.frameElement.remove()
  }
  log('PASS performance sample: exact two-page convergence, stable instances, no remote echo')
  const a = await client('preview'), b = await client('edit')
  await a.api.bootstrap(source); await b.api.load(a.api.checkpoint())
  await until(() => a.dom.querySelector('.markdown-body strong') && b.api.view(), 'large preview missing')
  a.api.remember(); b.api.remember()
  selectRenderedText(a, '.markdown-body strong', 0, 4)
  const anchor = a.api.editor().captureAnchor()
  assert(anchor, 'initial large preview selection failed')
  a.api.editor().renderAnchors([{ id: 'large-comment', anchor }])
  b.api.select(0); b.api.insert('prefix '); sync(b, a)
  assert(a.api.editor().captureAnchor() === null, 'stale preview projection accepted')
  assert(await a.api.exportFile().blob.text() === b.api.text(), 'export read stale preview')
  await until(() => a.dom.querySelector('.markdown-body').textContent.startsWith('prefix ')
    && a.dom.querySelector('.preview-pane').getAttribute('aria-busy') === 'false', 'preview did not settle')
  await pause(80)
  const restored = a.api.editor().captureAnchor()
  assert(restored && a.api.editor().resolveAnchor(restored).from === a.api.editor().resolveAnchor(anchor).from, 'preview selection not restored through delayed remote render')
  assert(a.dom.querySelector('.exmd-preview-comment'), 'delayed comments missing')
  assert(a.api.editor().revealAnchor(anchor) && a.dom.querySelector('.editor-pane').hidden, 'preview reveal switched source')
  b.api.editor().undo(); sync(b, a)
  await until(() => !a.dom.querySelector('.markdown-body').textContent.startsWith('prefix ')
    && a.dom.querySelector('.preview-pane').getAttribute('aria-busy') === 'false', 'undo preview did not settle')
  same(a, b)
  a.api.previewDelay(0); await pause(80)
  b.api.select(0); b.api.insert('immediate '); sync(b, a); await pause(80)
  assert(a.dom.querySelector('.preview-pane').getAttribute('aria-busy') === 'false', 'zero delay ignored')
  assert(a.api.stable() && b.api.stable() && a.api.count().pending === 0, 'delay/profile update remounted or echoed')
  log('PASS delayed preview selection refuses stale offsets, restores relative anchors/comments; export stays current; undo and delay=0 preserve instances')
}
