export function selectRenderedText(client, selector, from, to, occurrence = 0) {
  const element = client.dom.querySelectorAll(selector)[occurrence]
  if (!element) throw new Error('Missing selection target: ' + selector)
  const nodes = [], walker = client.dom.createTreeWalker(element, 4)
  for (let node = walker.nextNode(); node; node = walker.nextNode()) nodes.push(node)
  const point = offset => {
    for (const node of nodes) { if (offset <= node.length) return [node, offset]; offset -= node.length }
    throw new Error('Invalid rendered text offset')
  }
  const range = client.dom.createRange()
  range.setStart(...point(from)); range.setEnd(...point(to))
  client.api.view()?.contentDOM.blur()
  element.dispatchEvent(new client.dom.defaultView.PointerEvent('pointerdown', { bubbles: true }))
  const selection = client.dom.getSelection(); selection.removeAllRanges(); selection.addRange(range)
  client.dom.dispatchEvent(new client.dom.defaultView.Event('selectionchange'))
  return range
}

export async function runPreviewSuite({ client, pause, assert, until, sync, same, button, log }) {
  const source = '# Heading\n\nAlpha **Bravo** Charlie\n\nAlpha Bravo Charlie\n\nNested **Br*av*o** [Label](https://example.test)\n\n> lineOne\n> lineTwo\n\nRepeat Bravo and Bravo\n\nA &amp; B \\* C ` a  b\nc `\n\nHard  \nBreak\n\n- listOne\n  listTwo\n\n| ColOne | ColTwo |\n| --- | --- |\n| cellA | cellB |\n'
  const a = await client('preview'), b = await client()
  await a.api.bootstrap(source); await b.api.load(a.api.checkpoint())
  await until(() => a.api.view() && b.api.view() && a.dom.querySelector('[data-exmd-text]'), 'preview mappings not ready')
  a.api.remember(); b.api.remember(); a.api.watch()
  const before = a.api.count()
  const capture = () => a.api.editor().captureAnchor()
  const resolve = anchor => a.api.editor().resolveAnchor(anchor)
  const expectRange = (expectedFrom, expectedTo, message) => {
    const anchor = capture(), range = anchor && resolve(anchor)
    assert(range?.from === expectedFrom && range.to === expectedTo,
      message + ': ' + JSON.stringify({ range, expectedFrom, expectedTo }))
    return anchor
  }
  selectRenderedText(a, '.markdown-body strong', 0, 5)
  const bravo = expectRange(source.indexOf('**Bravo**') + 2, source.indexOf('**Bravo**') + 7, 'five-character bold selection')
  assert(resolve(bravo).to - resolve(bravo).from === 5, 'paragraph/line anchor substituted')
  a.api.select(0, 7) // Leave a valid but unrelated source selection behind.
  selectRenderedText(a, '.markdown-body strong', 0, 5)
  a.dom.getSelection().removeAllRanges()
  assert(capture() === null, 'preview fell back to stale source selection')
  selectRenderedText(a, '.markdown-body p', 6, 11, 1)
  expectRange(source.indexOf('Alpha Bravo') + 6, source.indexOf('Alpha Bravo') + 11, 'repeated text in another paragraph')
  selectRenderedText(a, '.markdown-body p', 17, 22, 4)
  expectRange(source.indexOf('and Bravo') + 4, source.indexOf('and Bravo') + 9, 'repeated text on the same line')
  log('PASS exact five characters; duplicate text in same line/other paragraph; no stale source fallback')

  selectRenderedText(a, '.markdown-body p', 8, 15, 2) // ravo La, crossing nested strong/em and a link.
  expectRange(source.indexOf('Br*av') + 1, source.indexOf('[Label]') + 3, 'nested formatting and link partial range')
  selectRenderedText(a, '.markdown-body a', 1, 4)
  expectRange(source.indexOf('[Label]') + 2, source.indexOf('[Label]') + 5, 'link label excludes destination')
  selectRenderedText(a, '.markdown-body blockquote p', 4, 12)
  expectRange(source.indexOf('lineOne') + 4, source.indexOf('lineTwo') + 4, 'blockquote soft break and prefix')
  selectRenderedText(a, '.markdown-body p', 2, 3, 5)
  expectRange(source.indexOf('&amp;'), source.indexOf('&amp;') + 5, 'entity maps whole encoded character')
  selectRenderedText(a, '.markdown-body p', 6, 7, 5)
  expectRange(source.indexOf('\\*'), source.indexOf('\\*') + 2, 'escaped punctuation')
  selectRenderedText(a, '.markdown-body code', 1, 5)
  expectRange(source.indexOf('` a  b') + 3, source.indexOf('` a  b') + 7, 'inline code normalized padding/newline')
  selectRenderedText(a, '.markdown-body p', 2, 8, 6)
  expectRange(source.indexOf('Hard') + 2, source.indexOf('Break') + 3, 'hard line break')
  selectRenderedText(a, '.markdown-body li', 4, 12)
  expectRange(source.indexOf('listOne') + 4, source.indexOf('listTwo') + 4, 'list continuation indentation')
  selectRenderedText(a, '.markdown-body td', 1, 4, 1)
  expectRange(source.indexOf('cellB') + 1, source.indexOf('cellB') + 4, 'table cell character range')
  log('PASS nested marks/link labels, soft/hard line breaks, entities/escapes, inline code, lists and tables')

  const c1 = { id: 'preview-bravo', anchor: bravo }
  const c2 = a.api.comment('overlap', resolve(bravo).from + 2, resolve(bravo).to)
  a.api.editor().renderAnchors([c1, c2]); await pause(80)
  assert(a.dom.querySelectorAll('.exmd-preview-comment').length >= 2, 'preview underline missing')
  assert(a.dom.querySelectorAll('.exmd-comment-anchor').length >= 2, 'source snapshot missing')
  a.api.editor().setActiveAnchor(c1.id); await pause(60)
  assert(a.dom.querySelector('.exmd-preview-comment-active') && a.dom.querySelector('.exmd-comment-active'), 'shared active background')
  assert(a.api.editor().revealAnchor(bravo) && a.dom.querySelector('.editor-pane').hidden, 'preview reveal forced source view')
  const clickRegion = async () => {
    a.dom.getSelection().removeAllRanges()
    const range = selectRenderedText(a, '.markdown-body strong', 3, 4)
    const rect = range.getBoundingClientRect(); a.dom.getSelection().collapseToStart()
    range.startContainer.parentElement.dispatchEvent(new a.dom.defaultView.MouseEvent('click', {
      bubbles: true, cancelable: true, clientX: rect.left + rect.width / 2, clientY: rect.top + rect.height / 2,
    }))
    await pause(60)
  }
  await clickRegion(); const first = a.api.clicks().at(-1)
  await clickRegion(); const second = a.api.clicks().at(-1)
  assert(first !== second && [first, second].includes(c1.id) && [first, second].includes(c2.id), 'overlap click cannot reach each comment')
  a.api.editor().setActiveAnchor(null); await pause(60)
  assert(!a.dom.querySelector('.exmd-preview-comment-active') && !a.dom.querySelector('.exmd-comment-active'), 'clear activation')
  log('PASS shared underline/background, preview card reveal, overlapping comment cycling, clear activation')

  a.api.readonly(true); await pause(60)
  selectRenderedText(a, '.markdown-body strong', 0, 5); await pause(80)
  const floating = a.dom.querySelector('.exmd-selection-toolbar button')
  assert(floating && !floating.disabled, 'readonly incorrectly disabled comment permission')
  const selected = a.dom.getSelection().toString()
  const down = new a.dom.defaultView.MouseEvent('mousedown', { bubbles: true, cancelable: true })
  floating.dispatchEvent(down); assert(down.defaultPrevented, 'action does not preserve native selection')
  floating.click()
  assert(a.dom.getSelection().toString() === selected && a.api.actionEvents().at(-1)?.view === 'preview', 'action lost selection/view')
  assert(resolve(a.api.actionEvents().at(-1).anchor).to - resolve(a.api.actionEvents().at(-1).anchor).from === 5, 'action anchor incorrect')
  a.api.actionOptions(false); await pause(60)
  assert(!a.dom.querySelector('.exmd-selection-toolbar') && !a.dom.querySelector('.toolbar .exmd-host-actions button').disabled, 'top action fallback')
  a.dom.querySelector('.toolbar .exmd-host-actions button').click()
  a.api.actionOptions(false, true); await pause(60)
  assert(a.dom.querySelector('.toolbar .exmd-host-actions button').disabled, 'host comment permission ignored')
  assert(a.api.editor().insertText('forbidden') === false, 'readonly content guard')
  log('PASS readonly comment permission, native selection retention, host callback, top fallback and disabled permission')

  assert(a.api.count().pending === before.pending && a.api.count().changes === before.changes, 'comments/actions emitted content writes')
  a.api.actionOptions(true); a.api.readonly(false); await pause(50)
  selectRenderedText(a, '.markdown-body strong', 0, 5)
  b.api.select(0); b.api.insert('remote prefix\n\n'); sync(b, a); await pause(100)
  assert(resolve(bravo).from === source.indexOf('**Bravo**') + 2 + 15, 'remote insert anchor drift')
  expectRange(resolve(bravo).from, resolve(bravo).to, 'live preview selection after remote insertion')
  b.api.select(resolve(bravo).from + 2, resolve(bravo).from + 3); b.api.insert(''); sync(b, a); await pause(100)
  assert(a.dom.querySelector('.markdown-body strong').textContent === 'Brvo', 'remote deletion projection')
  expectRange(resolve(bravo).from, resolve(bravo).to, 'live preview selection after remote deletion')
  button(a, '分栏'); await pause(60)
  a.api.view().focus(); a.api.select(0); a.api.insert('local '); sync(a, b); await pause(100); same(a, b)
  a.api.select(resolve(bravo).from, resolve(bravo).to)
  assert(resolve(capture()).from === resolve(bravo).from, 'source active capture after preview')
  button(a, '仅预览'); await pause(60)
  a.api.editor().revealAnchor(bravo); await pause(60)
  a.dom.querySelector('.exmd-editor').style.zoom = '1.25'
  a.dom.querySelector('.preview-pane').scrollTop += 15
  a.dom.defaultView.dispatchEvent(new a.dom.defaultView.Event('resize')); await pause(100)
  const selectedRange = selectRenderedText(a, '.markdown-body strong', 0, 4)
  const visible = selectedRange.getBoundingClientRect()
  const mark = a.dom.querySelector('[data-comment-id="preview-bravo"].exmd-preview-comment')?.getBoundingClientRect()
  assert(mark && Math.abs(mark.left - visible.left) < 2 && Math.abs(mark.right - visible.right) < 2, 'zoom/scroll overlay drift')
  log('PASS local/remote insert-delete, retained relative selection, view switching and zoom/scroll geometry')

  a.api.editor().renderAnchors([{ ...c1, resolved: true }, { ...c2, deleted: true }]); await pause(60)
  assert(!a.dom.querySelector('.exmd-preview-comment') && !a.dom.querySelector('.exmd-comment-anchor'), 'resolved/deleted still visible')
  a.api.editor().renderAnchors([c1]); await pause(60)
  a.api.editor().clearAnchors(); await pause(60)
  assert(!a.dom.querySelector('.exmd-preview-comment'), 'clear did not remove preview decorations')
  a.api.editor().renderAnchors([c1]); const full = resolve(bravo)
  b.api.select(full.from, full.to); b.api.insert(''); sync(b, a); await pause(100)
  assert(resolve(bravo) === null && !a.dom.querySelector('.exmd-preview-comment'), 'fully deleted comment remains attached')
  assert(a.api.stable() && b.api.stable(), 'model/view/handle rebuilt')
  assert(Object.values(a.api.effects()).every(n => n === 0), 'SDK created network/storage')
  log('PASS resolve/delete/remove/orphan cleanup, stable instances and zero SDK transport/storage')
  const e = await client('preview')
  const edge = '# Edge\r\n\r\n中文😀 &#x1F600; &copy; **bold**\r\nnext\r\n\r\n[ref][id]\r\n\r\n[id]: https://example.test\r\n\r\n<span data-color="#123456" data-exmd-text="0">Red</span>\r\n\r\n$$\r\nE=mc^2\r\n$$\r\n\r\n```js\r\nconst value = 1\r\n```'
  await e.api.bootstrap(edge)
  await until(() => e.dom.querySelector('.katex'), 'edge preview not ready')
  await pause(80)
  assert(e.api.text() === edge && e.api.view().state.doc.toString() === edge && e.api.count().pending === 0,
    'mount normalized original CRLF or changed model')
  const check = (from, to, message) => {
    const anchor = e.api.editor().captureAnchor(), range = anchor && e.api.editor().resolveAnchor(anchor)
    assert(range?.from === from && range.to === to, message + ': ' + JSON.stringify(range))
  }
  selectRenderedText(e, '.markdown-body p', 2, 4)
  check(edge.indexOf('😀'), edge.indexOf('😀') + 2, 'UTF-16 emoji')
  selectRenderedText(e, '.markdown-body p', 5, 7)
  check(edge.indexOf('&#x1F600;'), edge.indexOf('&#x1F600;') + 9, 'numeric supplementary entity')
  selectRenderedText(e, '.markdown-body a', 1, 3)
  check(edge.indexOf('[ref]') + 2, edge.indexOf('[ref]') + 4, 'reference link label')
  selectRenderedText(e, '.markdown-body [data-color]', 0, 3)
  check(edge.indexOf('Red'), edge.indexOf('Red') + 3, 'HTML color text cannot forge mapping')
  selectRenderedText(e, '.markdown-body strong', 1, 4)
  const boundary = e.dom.createRange(), strong = e.dom.querySelector('.markdown-body strong')
  boundary.setStart(strong, 0); boundary.setEnd(strong, strong.childNodes.length)
  e.dom.getSelection().removeAllRanges(); e.dom.getSelection().addRange(boundary)
  check(edge.indexOf('**bold**') + 2, edge.indexOf('**bold**') + 6, 'element boundary selection')
  selectRenderedText(e, '.markdown-body .katex', 0, 1)
  assert(e.api.editor().captureAnchor() === null, 'generated math must not approximate source positions')
  selectRenderedText(e, '.markdown-body pre', 0, 5)
  assert(e.api.editor().captureAnchor() === null, 'highlighted code must not approximate source positions')
  assert(e.api.text() === edge && e.api.count().pending === 0, 'edge selection emitted model writes')
  log('PASS Unicode/CRLF, reference links, safe HTML color, element boundaries and unsupported content rejection')
}
